CREATE DATABASE IF NOT EXISTS sanjose;
USE sanjose;
DROP TABLE IF EXISTS ACCT;
CREATE TABLE ACCT (
  ID VARCHAR(10),
  BAL INT
);
INSERT INTO ACCT VALUES ('A', 100);
INSERT INTO ACCT VALUES ('B', 1000);
COMMIT;
SELECT * FROM ACCT;
