USE sanjose;
SET AUTOCOMMIT = 0;
SELECT * FROM ACCT;
INSERT INTO ACCT VALUES ('C', 200);
SELECT * FROM ACCT;
-- Switch to iso3_tx2 and run SELECT ID FROM ACCT WHERE BAL = 200;
COMMIT;
SELECT * FROM ACCT;
